version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - $HOME/mysql/data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: customeranalytics
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
       - 3306:3306
